spring.application.name=freelancer-toolkit-backend
server.port=8081
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/freelancertoolkit
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true